### ISSUE TITLE
result.php should use HTTPS if served over HTTPS

### ISSUE THREAD

**Issue by martymcguire** [Ruxton/indieweb-bestnine#2]
using the service at https://bestnine.indieweb.app/ for my site (https://martymcgui.re/posts/) and was stuck on the "creating your photo" step for a while.

Looking at the Network tab in Firefox dev tools, I see that it's trying to load the resulting image over http, and Firefox is blocking that as mixed content:

![Screenshot from 2020-01-14 10-29-51](https://user-images.githubusercontent.com/14772/72357364-d560e180-36b8-11ea-8df9-6887a0c79fd1.png)

There are a few places in the code where "http://..." is hardcoded as the destination protocol. Some of them could probably be replaced with "protocol relative" URLs ("//..."), some still need an explicit protocol.

**Comment by Ruxton** [comment]
Good catch, cheers @martymcguire

**Comment by Ruxton** [comment]
Fixed in 5d4a0ee28ba1292805e1bebcb2900ff02f79ef97
